// One word... TrackerCougerFalconBird
#define TRACKERBIRD_PRODUCT_ID L"2383178362"
#define TRACKERBIRD_URL L"http://85629.tbnet1.com"
#define TRACKERBIRD_PRODUCT_VERSION L"0.2.3"
#define TRACKERBIRD_BUILD_NUMBER L"0"
#define TRACKERBIRD_MULTISESSION_ENABLED FALSE
